name: Deploy to GCP

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: your-gcp-project-id # TODO: Replace with your GCP project ID
  GCP_REGION: us-central1
  GCR_REPOSITORY_NAME: agent-mesh-repo
  GKE_CLUSTER_NAME: agent-mesh-cluster
  WORKING_DIRECTORY: backend

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./${{ env.WORKING_DIRECTORY }}/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="gcp_project_id=${{ env.GCP_PROJECT_ID }}"
        working-directory: ./${{ env.WORKING_DIRECTORY }}/terraform

  build-and-deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}/agent-mesh:${{ github.sha }} .
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}/agent-mesh:${{ github.sha }}
        working-directory: ./${{ env.WORKING_DIRECTORY }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --region ${{ env.GCP_REGION }}

      - name: Update Kubernetes deployment image
        run: |
          sed -i 's|image: agent-mesh:latest|image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}/agent-mesh:${{ github.sha }}|g' kubernetes/deployment.yaml
        working-directory: ./${{ env.WORKING_DIRECTORY }}

      - name: Deploy to GKE
        run: kubectl apply -f kubernetes/
        working-directory: ./${{ env.WORKING_DIRECTORY }}
